services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coupon_Service
    image: yajanthrr/couponservice:v1
    environment:
      - SPRING_PROFILES_ACTIVE = docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/servicedb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATABASE_PASSWORD}
    ports:
      - "9095:9095"
    # restart: on-failure
    depends_on:
      - db
    networks:
      - springboot-network

  db:
    image: yajanthrr/coupondb:v1 
    container_name: coupon_database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    # restart: always
    ports:
      - "3307:3306"  # Host port mapped to container's MySQL port for external access
    volumes:
      - db_data:/var/lib/mysql   
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge

volumes:
  db_data: